Repository morpheusgraphql/morpheus-graphql, pull requests merged in 2022-04, with the labels that each got.

#710 test on labels
  .github/workflows/on-labels.yaml
Labels: pr/chore, pr/release

#723 Allow bytestring-0.11
  examples/client/morpheus-graphql-examples-client.cabal
  examples/client/package.yaml
  examples/code-gen/morpheus-graphql-examples-code-gen.cabal
  examples/code-gen/package.yaml
  examples/scotty/morpheus-graphql-examples-scotty.cabal
  examples/scotty/package.yaml
  examples/servant/morpheus-graphql-examples-servant.cabal
  examples/servant/package.yaml
  morpheus-graphql-app/morpheus-graphql-app.cabal
  morpheus-graphql-app/package.yaml
  morpheus-graphql-benchmarks/morpheus-graphql-benchmarks.cabal
  morpheus-graphql-benchmarks/package.yaml
  morpheus-graphql-client/morpheus-graphql-client.cabal
  morpheus-graphql-client/package.yaml
  morpheus-graphql-code-gen/morpheus-graphql-code-gen.cabal
  morpheus-graphql-code-gen/package.yaml
  morpheus-graphql-core/morpheus-graphql-core.cabal
  morpheus-graphql-core/package.yaml
  morpheus-graphql-subscriptions/morpheus-graphql-subscriptions.cabal
  morpheus-graphql-subscriptions/package.yaml
  morpheus-graphql-tests/morpheus-graphql-tests.cabal
  morpheus-graphql-tests/package.yaml
  morpheus-graphql/morpheus-graphql.cabal
  morpheus-graphql/package.yaml
Labels: dependencies

#725 stack config yaml
  config/stack.json
  config/stack.yaml
  morpheus-graphql-app/morpheus-graphql-app.cabal
  morpheus-graphql-app/package.yaml
  morpheus-graphql-client/morpheus-graphql-client.cabal
  morpheus-graphql-client/package.yaml
  morpheus-graphql-code-gen/morpheus-graphql-code-gen.cabal
  morpheus-graphql-code-gen/package.yaml
  morpheus-graphql-core/morpheus-graphql-core.cabal
  morpheus-graphql-core/package.yaml
  morpheus-graphql-subscriptions/morpheus-graphql-subscriptions.cabal
  morpheus-graphql-subscriptions/package.yaml
  morpheus-graphql-tests/morpheus-graphql-tests.cabal
  morpheus-graphql-tests/package.yaml
  morpheus-graphql/morpheus-graphql.cabal
  morpheus-graphql/package.yaml
  scripts/lib/check-packages/types.ts
  scripts/lib/utils/file.ts
Labels: pr/chore

#727 Local/Global Type Generation
  Makefile
  config/stack.yaml
  config/stack/latest.yaml
  examples/client/src/Client/DefineByIntrospection.hs
  examples/client/src/Client/Mythology.hs
  examples/client/src/Client/StarWarsClient.hs
  examples/scotty/src/Server/Fraxl/API.hs
  examples/scotty/src/Server/Fraxl/FakeDB.hs
  morpheus-graphql-client/morpheus-graphql-client.cabal
  morpheus-graphql-client/package.yaml
  morpheus-graphql-client/src/Data/Morpheus/Client.hs
  morpheus-graphql-client/src/Data/Morpheus/Client/Build.hs
  morpheus-graphql-client/src/Data/Morpheus/Client/Declare.hs
  morpheus-graphql-client/src/Data/Morpheus/Client/Declare/Client.hs
  morpheus-graphql-client/src/Data/Morpheus/Client/Declare/Fetch.hs
  morpheus-graphql-client/src/Data/Morpheus/Client/Fetch.hs
  morpheus-graphql-client/src/Data/Morpheus/Client/Internal/Types.hs
  morpheus-graphql-client/src/Data/Morpheus/Client/Internal/Utils.hs
  morpheus-graphql-client/src/Data/Morpheus/Client/QuasiQuoter.hs
  morpheus-graphql-client/src/Data/Morpheus/Client/Schema/JSON/Parse.hs
  morpheus-graphql-client/src/Data/Morpheus/Client/Schema/JSON/TypeKind.hs
  morpheus-graphql-client/src/Data/Morpheus/Client/Schema/JSON/TypeRef.hs
  morpheus-graphql-client/src/Data/Morpheus/Client/Schema/JSON/Types.hs
  morpheus-graphql-client/src/Data/Morpheus/Client/Schema/Parse.hs
  morpheus-graphql-client/src/Data/Morpheus/Client/Transform.hs
  morpheus-graphql-client/src/Data/Morpheus/Client/Transform/Inputs.hs
  morpheus-graphql-client/src/Data/Morpheus/Client/Transform/Selection.hs
  morpheus-graphql-client/test/Case/Github/Test.hs
  morpheus-graphql-client/test/Case/LocalGlobal/Api.hs
  morpheus-graphql-client/test/Case/LocalGlobal/Test.hs
  morpheus-graphql-client/test/Case/LocalGlobal/cities.json
  morpheus-graphql-client/test/Case/LocalGlobal/schema.gql
  morpheus-graphql-client/test/Case/LocalGlobal/users1.gql
  morpheus-graphql-client/test/Case/LocalGlobal/users1.json
  morpheus-graphql-client/test/Case/LocalGlobal/users2.gql
  morpheus-graphql-client/test/Case/LocalGlobal/users2.json
  morpheus-graphql-client/test/Case/LowercaseTypeName/Test.hs
  morpheus-graphql-client/test/Case/Scalar/Test.hs
  morpheus-graphql-client/test/Spec.hs
  morpheus-graphql-client/test/Spec/Utils.hs
  stack.yaml
Labels: scope/client, pr/breaking
